name: Run tests
env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Build application
        run: npm run build

      - name: Enable initializers for unit testing
        run: sed -i 's/_disableInitializers();/\/\/_disableInitializers();/g' contracts/core/TokenTableUnlockerV2.sol && sed -i 's/_disableInitializers();/\/\/_disableInitializers();/g' contracts/core/TTTrackerTokenV2.sol && sed -i 's/_dummyInitialize();/\/\/_dummyInitialize();/g' contracts/core/TTFutureTokenV2.sol

      - name: Run tests
        run: npm test

      - name: Revert changes made for unit testing
        run: sed -i 's/\/\/_disableInitializers();/_disableInitializers();/g' contracts/core/TokenTableUnlockerV2.sol && sed -i 's/\/\/_disableInitializers();/_disableInitializers();/g' contracts/core/TTTrackerTokenV2.sol && sed -i 's/\/\/_dummyInitialize();/_dummyInitialize();/g' contracts/core/TTFutureTokenV2.sol

  TypeScript-Static-Analyis:
    runs-on: ubuntu-latest
    name: TypeScript static analysis
    needs: Unit-Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Build application
        run: npm run build

      - name: Lint
        run: npm run lint-ts

  Solidity-Static-Analysis-Solhint:
    runs-on: ubuntu-latest
    name: Solidity static analysis (Solhint)
    needs: Unit-Tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Build application
        run: npm run build

      - name: Lint
        run: npm run lint-sol


  Solidity-Static-Analysis-Slither:
    runs-on: ubuntu-latest
    name: Solidity static analysis (Slither)
    needs: Unit-Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Set up cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Slither Static Analysis
        run: slither . --config-file slither.json
